comment: false

codecov:
  require_ci_to_pass: false

coverage:
  precision: 1
  round: down
  range: "90...100"
  status:
    project:
      default:
        threshold: 85%

      generator:
        threshold: 80%
        paths:
          - generator/

      fuzzer:
        threshold: 90%
        paths:
          - fuzzer/

      evaluator:
        threshold: 85%
        paths:
          - evaluator/

    patch:
      default:
        threshold: 90%
        if_not_found: failure
