comment: false

codecov:
  require_ci_to_pass: false

coverage:
  precision: 1
  round: down
  range: "90...100"
  status:
    project:
      default:
        target: 81%

      generator:
        target: 87%
        paths:
          - generator/

      fuzzer:
        target: 90%
        paths:
          - fuzzer/

      evaluator:
        target: 61%
        paths:
          - evaluator/

    patch:
      default:
        target: 80%
        only_pulls: true
