= kwik

image:https://img.shields.io/badge/License-Apache%202.0-blue.svg[link="LICENSE"]
image:https://img.shields.io/badge/status-incubating-orange.svg[link="https://gist.githubusercontent.com/jcornaz/46736c3d1f21b4c929bd97549b7406b2/raw/ProjectStatusFlow"]
image:https://travis-ci.com/jcornaz/kwik.svg?branch=master["Build Status", link="https://travis-ci.com/jcornaz/kwik"]
image:https://api.bintray.com/packages/kwik/preview/kwik/images/download.svg[link="https://bintray.com/kwik/preview/kwik/_latestVersion"]

Property-based testing library for Kotlin.

.Main features
* Test-engine agnostic (Mix property-based tests with example-based tests written for the engine of your choice)
* Multiplatform
* No reflection (better compile-time feedback and faster runtime)
* Configurable built-in generators
* Easy way to create and combine generators

== Status

The project is incubating and its API may change in the future.

Please give it a try and give feed back in the link:https://github.com/jcornaz/kwik/issues[issues].

== Motivation

Property based testing is great and very powerful. But despite the fact that many good libraries already exist,
none of them fully fit my needs.

.Here is a review of the existing alternatives:
* link:https://jqwik.net/[jqwik] and link:https://github.com/pholser/junit-quickcheck[junit-quickcheck]
    ** :+1: Excellent API
    ** :+1: Feature rich
    ** :-1: Tight to test engines (Junit4 for `junit-quickcheck` and `jqwik` needs its own engine)
    ** :-1: Heavily rely on reflection (Making it slower than it could be and many errors are only reported at runtime)
    ** :-1: Java library
        *** Disable some Kotlin powerful features (like null safety)
        *** Cannot be used in Kotlin Common, JavaScript or Native code
* link:https://github.com/mike-neck/kuickcheck[kuickcheck]
    ** :+1: Kotlin API
    ** :-1: Is a test-engine
    ** :-1: Rely on reflection (Making it slower than it could be and many errors are only reported at runtime)
    ** :-1: Api not as safe as it could be
    ** :-1: Not published, and seems discontinued
* link:https://github.com/kotlintest/kotlintest[KotlinTest]
    ** :+1: Safe Kotlin API
    ** :+1: Not tight to any test-engine
    ** :-1: Force the user to add unwanted modules into his/her classpath +
            (namely `kotlintest-assertions`, `kotlin-reflect`, `univocity-parsers` and `diffutils`)
    ** :-1: Generators are not configurable, making it slow by design
    ** :-1: Perform too many iterations by default (making tests slow)
    ** :-1: Cannot be used in Kotlin Common, JavaScript or Native code


== Installation

Latest version: image:https://api.bintray.com/packages/kwik/preview/kwik/images/download.svg[link="https://bintray.com/kwik/preview/kwik/_latestVersion"]

1. Add https://dl.bintray.com/kwik/preview to your maven repositories
2. Add `com.github.jcornaz.kwik:kwik-core-jvm:<version>` as a dependency
   (replacing `jvm` by `common` in case of a common module, and replacing `<version>` by the latest version (see above))

.Example with Gradle (Kotlin DSL)
[source,kotlin]
----
repositories {
    maven { url = uri("https://dl.bintray.com/kwik/preview") }
}

dependencies {

    // in a JVM module
    testCompile("com.github.jcornaz.kwik:kwik-core-jvm:<version>")

    // in a common (multiplatform) module
    testCompile("com.github.jcornaz.kwik:kwik-core-common:<version>")
}
----
