= kwik

image:https://img.shields.io/badge/License-Apache%202.0-blue.svg[link="LICENSE"]
image:https://img.shields.io/badge/status-incubating-orange.svg[link="https://gist.githubusercontent.com/jcornaz/46736c3d1f21b4c929bd97549b7406b2/raw/ProjectStatusFlow"]
image:https://travis-ci.com/jcornaz/kwik.svg?branch=master["Build Status", link="https://travis-ci.com/jcornaz/kwik"]
image:https://api.bintray.com/packages/kwik/preview/kwik/images/download.svg[link="https://bintray.com/kwik/preview/kwik/_latestVersion"]

Property-based testing library for Kotlin.

.Main features
* Test-engine agnostic (Mix property-based tests with example-based tests written for the engine of your choice)
* Multiplatform
* No reflection (better compile-time feedback and faster runtime)
* Configurable built-in generators
* Easy way to create and combine generators

== Status

The project is incubating and its API may change in the future.

Please give it a try and give feed back in the link:https://github.com/jcornaz/kwik/issues[issues].

== Motivation

Property based testing is great and very powerful. But despite the fact that many good libraries already exist,
none of them fully fit my needs.

.The existing alernatives often:
* Are bound to a specific test-engine
* Can only be used in Java module (not in Koltin multiplatform modules)
* Relies on reflection, making them slower then it could be and make some error detectable only at runtime
* Some of them also force the user to add unwanted dependencies in his/her classpath

== Installation

Latest version: image:https://api.bintray.com/packages/kwik/preview/kwik/images/download.svg[link="https://bintray.com/kwik/preview/kwik/_latestVersion"]

1. Add https://dl.bintray.com/kwik/preview to your maven repositories
2. Add `com.github.jcornaz.kwik:kwik-core-jvm:<version>` as a dependency
   (replacing `jvm` by `common` in case of a common module, and replacing `<version>` by the latest version (see above))

.Example with Gradle (Kotlin DSL)
[source,kotlin]
----
repositories {
    maven { url = uri("https://dl.bintray.com/kwik/preview") }
}

dependencies {

    // in a JVM module
    testCompile("com.github.jcornaz.kwik:kwik-core-jvm:<version>")

    // in a common (multiplatform) module
    testCompile("com.github.jcornaz.kwik:kwik-core-common:<version>")
}
----
