name: Publish reference

on:
  push:
    tags:
      - '*'

  pull_request:
    branches:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle
          key: gradle-cache-ubuntu-java11-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/*.kt*') }}
          restore-keys: gradle-cache-ubuntu-java11-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Build reference
        run: ./gradlew dokkaHtmlMultimodule --no-daemon

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/dokka/htmlMultimodule
